## Add your devices here:
#devices:
#    - name: Shunt1
#      type: smartshunt
#      protocol: bluetooth
#      mac: fd:d4:50:0f:6c:1b
#    - name: Phoenix1
#      type: pheonix
#      protocol: serial
#      port: /dev/ttyUSB0

devices:
    - name: Shunt1
      type: smartshunt
      protocol: bluetooth
      mac: fd:d4:50:0f:6c:1b
    - name: Solar1
      type: smartsolar
      protocol: bluetooth
      mac: F9:8E:1C:EC:9C:72
    - name: Orion1
      type: orionsmart
      protocol: bluetooth
      mac: E7:79:E6:1D:EF:04
    - name: Phoenix1
      type: pheonix
      protocol: serial
      port: /dev/ttyUSB0

# timer (in seconds)
#
#
# repeat: 60
#   - Will be used only if run programm in default time mode (Disconnection from device after collection is finished)
#   - It repeats connecting after given time, regardless at which time it was disconnected
#
timer:
    connected: 30  # timer how long the device is connected
    disconnected: 30 # timer at which time the device is connected again after disconnect # during dev. for prod: 2 * 60
    repeat: 180
    retry: 30
    serial: 30  # timer how long serial data mining will sleep (data can be gathered every second)

## Logging:
## possible values:
##    - syslog
##    - mqtt
logger: mqtt

## If logging is set to mqtt, these values must be filled
mqtt:
    host: 192.168.3.2
    port: 1883
    base_topic: victron

# Collected enitites by device type:
# If you change this, the names must be the same like in the value tables from victron.py
# These are the needed values to send a collection to logger, if other values are gathered (Usually they are from time to time), they are added to the collection too
collections:
  smartshunt:
    product:
      - Serial
      - Firmware Version
      - Udf version
    battery:
      - Charge Status
      - Time to go
    latest:
      - Voltage
      - Current
      - Power
      - Starter
    history:
      - Deepest Discharge
      - Last Discharge
      - Average Discharge
      - Cumulative Ah Drawn
      - Time Since Last Full
  smartsolar:
    latest:
      - Voltage
      - SmartSolar Power
      - SmartSolar Solar Voltage
      - SmartSolar Solar Current
      - SmartSolar Battery Current
    history:
      - Battery Voltage Max
      - Battery Voltage Min
      - Total Work
      - Solar Power Max
      - Solar Voltage Max
